version: "3"

services:
  php:
    build: ./php
    container_name: "codeigniter-local"
    volumes:
      - ./php:/var/www/html
    ports:
      - "80:80"

  db:
    container_name: "mysql-local"
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cafe_log
    volumes:
      - ./db/mysql_data:/var/lib/mysql
